simple_model:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 20

  base_to_first_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: base_to_first_joint
    pid: {p: 6.0, i: 1.0, d: 1.0}

  first_to_second_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: first_to_second_joint
    pid: {p: 6.0, i: 1.0, d: 1.0}

  end_effector_to_latch_position_controller:
    type: effort_controllers/JointPositionController
    joint: end_effector_to_latch
    pid: {p: 10.0, i: 0, d: 0}

  base_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: base_link_joint
    pid: {p: 5, i: 1, d: 1}