simple_model:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  base_to_first_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: base_to_first_joint
    pid: {p: 40.0, i: 4, d: 0.5}

  first_to_second_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: first_to_second_joint
    pid: {p: 40.0, i: 4, d: 0.5}

  end_effector_to_latch_position_controller:
    type: effort_controllers/JointPositionController
    joint: end_effector_to_latch
    pid: {p: 10, i: 1, d: 0}

  base_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: base_link_joint
    pid: {p: 10, i: 1, d: 1}